#!/usr/bin/zsh

set -eu


readonly EX_USAGE=64
readonly EX_NOINPUT=66

usage() {
    echo "usage: $(basename "$0") This functions converts the jupyter notebook to pdf and open it in okular" 
}

if [ $# -ne 1 ]; then
    usage
    exit $EX_USAGE
fi

if [ "$1" = -h ] || [ "$1" = --help ]; then
    usage
    exit
fi

if [ ! -f "$1" ]; then
    echo "$(basename "$0"): $1: No such file"
    exit $EX_NOINPUT
fi

jupyter nbconvert --to pdf "$1" 2>/dev/null
filename="${1%.*}"
okular "$filename.pdf"
rm "$filename.pdf"
