#!/usr/bin/zsh

set -eu

usage() {
    echo "Usage: slide [-t THEME] [-h] [-o] filenames \n  This function creates a reveal.js slide from a makdown files and open it in firefox."
}

THEME="simple"

while getopts ":ht:o" opt; do
	case "$opt" in
		t)
			THEME="$OPTARG"
			;;
		h)
			usage
			exit 1
			;;
		o) 
			echo "Option for theme:"
			echo "  beige\n  blood\n  league\n  night\n  simple\n  solarized\n  black\n  moon\n  serif\n  sky\n  white"
			exit 1
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument."
			exit 1
			;;
	esac
done
shift "(${OPTIND} - 1)"

if [ -z $* ]; then
	echo "Please provide the markdown files you want to be converted to sildes"
fi

for file in $* ; do
	# Separate the name from the extension
	FILENAME=${file%.*}

	pandoc -s --template ~/.myfunctions/assets/template.html -i -t revealjs $FILENAME.md -o $FILENAME.html

	# Change the theme if given
	if [[ ! -z "$THEME" ]];then
		sed -i 's/simple/'"$THEME"'/g' $FILENAME.html
	fi

	# Open the generated html file in firefox
	firefox $FILENAME.html
done
